import { Company } from "./work-samples";

export type BSLine = {
  label: string;
  amount: number | null;
  type: "header" | "subheader" | "line" | "subtotal" | "total" | "spacer";
  indent?: 0 | 1 | 2;
};

export type BalanceSheetVariant = {
  label: string;
  period: string;
  company: Company;
  theme: string;
  summary: string;
  totalAssets: number;
  totalLiabilities: number;
  totalEquity: number;
  currentRatio: number;
  debtToEquity: number;
  workingCapital: number;
  roe: number;
  lines: BSLine[];
};

export const BALANCE_SHEET_VARIANTS: BalanceSheetVariant[] = [
  {
    label: "Year-End Balance Sheet",
    period: "Dec 31, 2022",
    company: "fashion-house",
    theme: "Year-End",
    summary:
      "FY22 closing balance sheet. Current assets dominated by AR and cash; intangibles reflect brand and trademarks. Equity built from common shares plus retained earnings less dividends.",
    totalAssets: 1400900,
    totalLiabilities: 574225,
    totalEquity: 826675,
    currentRatio: 2.59,
    debtToEquity: 0.69,
    workingCapital: 721675,
    roe: 0.3347,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Current Assets", amount: null, type: "subheader" },
      { label: "Cash", amount: 432400, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 580000, type: "line", indent: 2 },
      { label: "Raw Materials Inventory", amount: 100000, type: "line", indent: 2 },
      { label: "Finished Goods Inventory", amount: 62000, type: "line", indent: 2 },
      { label: "Prepaid Insurance", amount: 1500, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 1175900, type: "subtotal", indent: 1 },
      { label: "Property & Equipment", amount: null, type: "subheader" },
      { label: "Studio & Showroom Equipment", amount: 180000, type: "line", indent: 2 },
      { label: "Less: Accumulated Depreciation", amount: -30000, type: "line", indent: 2 },
      { label: "Net Book Value, Equipment", amount: 150000, type: "subtotal", indent: 1 },
      { label: "Intangible Assets", amount: null, type: "subheader" },
      { label: "Brand & Design Portfolio", amount: 90000, type: "line", indent: 2 },
      { label: "Less: Accumulated Amortization", amount: -15000, type: "line", indent: 2 },
      { label: "Net Book Value, Intangibles", amount: 75000, type: "subtotal", indent: 1 },
      { label: "TOTAL ASSETS", amount: 1400900, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Current Liabilities", amount: null, type: "subheader" },
      { label: "Accounts Payable", amount: 340000, type: "line", indent: 2 },
      { label: "Salaries Payable", amount: 22000, type: "line", indent: 2 },
      { label: "Income Tax Payable", amount: 92225, type: "line", indent: 2 },
      { label: "Total Current Liabilities", amount: 454225, type: "subtotal", indent: 1 },
      { label: "Non-Current Liabilities", amount: null, type: "subheader" },
      { label: "Notes Payable", amount: 120000, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 574225, type: "subtotal" },
      { label: "SHAREHOLDERS' EQUITY", amount: null, type: "header" },
      { label: "Common Shares", amount: 600000, type: "line", indent: 2 },
      { label: "Net Income for the Year", amount: 276675, type: "line", indent: 2 },
      { label: "Less: Dividends Declared", amount: -50000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: 226675, type: "subtotal", indent: 1 },
      { label: "TOTAL SHAREHOLDERS' EQUITY", amount: 826675, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 1400900, type: "total" },
    ],
  },
  {
    label: "Month-End Balance Sheet",
    period: "Mar 31, 2024",
    company: "fashion-house",
    theme: "Month-End",
    summary:
      "March 2024 month-end balance sheet. Reflects payments cleared, payroll accruals, FX revaluation and quarter-end tax position. Retained earnings rolled forward from FY23.",
    totalAssets: 1492045,
    totalLiabilities: 593830,
    totalEquity: 898215,
    currentRatio: 2.27,
    debtToEquity: 0.66,
    workingCapital: 717585,
    roe: 0.0512,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Current Assets", amount: null, type: "subheader" },
      { label: "Cash, RBC Operating", amount: 318420, type: "line", indent: 2 },
      { label: "Cash, RBC USD", amount: 56820, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 642000, type: "line", indent: 2 },
      { label: "Raw Materials Inventory", amount: 142800, type: "line", indent: 2 },
      { label: "Finished Goods Inventory", amount: 88600, type: "line", indent: 2 },
      { label: "Prepaid Insurance", amount: 4125, type: "line", indent: 2 },
      { label: "GST/HST Receivable (ITC)", amount: 14820, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 1267585, type: "subtotal", indent: 1 },
      { label: "Property & Equipment, net", amount: 167500, type: "line", indent: 1 },
      { label: "Intangible Assets, net", amount: 56960, type: "line", indent: 1 },
      { label: "TOTAL ASSETS", amount: 1492045, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 384200, type: "line", indent: 2 },
      { label: "Accrued Liabilities", amount: 46800, type: "line", indent: 2 },
      { label: "Salaries Payable", amount: 16800, type: "line", indent: 2 },
      { label: "GST/HST Payable", amount: 31180, type: "line", indent: 2 },
      { label: "Income Tax Payable", amount: 24850, type: "line", indent: 2 },
      { label: "Total Current Liabilities", amount: 503830, type: "subtotal", indent: 1 },
      { label: "Notes Payable", amount: 90000, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 593830, type: "subtotal" },
      { label: "Common Shares", amount: 600000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: 298215, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 898215, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 1492045, type: "total" },
    ],
  },
  {
    label: "Foodservice Balance Sheet",
    period: "Mar 31, 2024",
    company: "foodservice",
    theme: "Month-End",
    summary:
      "Foodservice operator month-end balance sheet. Smaller AR (cash-and-card heavy revenue), modest inventory, payroll-driven current liabilities and multiple sales tax balances.",
    totalAssets: 419720,
    totalLiabilities: 299650,
    totalEquity: 120070,
    currentRatio: 0.9,
    debtToEquity: 2.5,
    workingCapital: -29270,
    roe: 0.087,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Current Assets", amount: null, type: "subheader" },
      { label: "Cash, RBC Operating", amount: 184500, type: "line", indent: 2 },
      { label: "Petty Cash", amount: 2000, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 24600, type: "line", indent: 2 },
      { label: "Food & Beverage Inventory", amount: 38400, type: "line", indent: 2 },
      { label: "Prepaid Rent", amount: 8400, type: "line", indent: 2 },
      { label: "GST/HST Receivable (ITC)", amount: 12480, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 270380, type: "subtotal", indent: 1 },
      { label: "Smallwares & Equipment", amount: 168000, type: "line", indent: 2 },
      { label: "Less: Accumulated Depreciation", amount: -42000, type: "line", indent: 2 },
      { label: "Property & Equipment, net", amount: 126000, type: "subtotal", indent: 1 },
      { label: "Leasehold Improvements, net", amount: 23340, type: "line", indent: 1 },
      { label: "TOTAL ASSETS", amount: 419720, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 184800, type: "line", indent: 2 },
      { label: "Accrued Liabilities", amount: 28400, type: "line", indent: 2 },
      { label: "Salaries Payable", amount: 32400, type: "line", indent: 2 },
      { label: "Source Deductions Payable", amount: 18510, type: "line", indent: 2 },
      { label: "GST/HST Payable", amount: 22440, type: "line", indent: 2 },
      { label: "QST Payable", amount: 9180, type: "line", indent: 2 },
      { label: "PST Payable, BC", amount: 3920, type: "line", indent: 2 },
      { label: "Total Current Liabilities", amount: 299650, type: "subtotal", indent: 1 },
      { label: "Note: TL=Current here", amount: null, type: "spacer" },
      { label: "TOTAL LIABILITIES", amount: 299650, type: "subtotal" },
      { label: "Common Shares", amount: 200000, type: "line", indent: 2 },
      { label: "Retained Earnings (Deficit)", amount: -79930, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 120070, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 419720, type: "total" },
    ],
  },
  {
    label: "Direct Sales Balance Sheet",
    period: "Mar 31, 2024",
    company: "direct-sales",
    theme: "Month-End",
    summary:
      "Direct sales operation month-end balance sheet. Heavy AR position, doubtful accounts allowance, commission payable line and accrued sales taxes from multi-jurisdiction operations.",
    totalAssets: 448245,
    totalLiabilities: 239190,
    totalEquity: 209055,
    currentRatio: 1.78,
    debtToEquity: 1.14,
    workingCapital: 185955,
    roe: 0.187,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Current Assets", amount: null, type: "subheader" },
      { label: "Cash, RBC Operating", amount: 124680, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 196340, type: "line", indent: 2 },
      { label: "Less: Allowance for Doubtful Accts", amount: -4920, type: "line", indent: 2 },
      { label: "Inventory, Finished Goods", amount: 84600, type: "line", indent: 2 },
      { label: "Prepaid Insurance", amount: 9625, type: "line", indent: 2 },
      { label: "GST/HST Receivable (ITC)", amount: 14820, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 425145, type: "subtotal", indent: 1 },
      { label: "Office Equipment", amount: 42000, type: "line", indent: 2 },
      { label: "Less: Accumulated Depreciation", amount: -18900, type: "line", indent: 2 },
      { label: "Property & Equipment, net", amount: 23100, type: "subtotal", indent: 1 },
      { label: "TOTAL ASSETS", amount: 448245, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 148790, type: "line", indent: 2 },
      { label: "Accrued Liabilities", amount: 27600, type: "line", indent: 2 },
      { label: "Commissions Payable", amount: 14820, type: "line", indent: 2 },
      { label: "Salaries Payable", amount: 16800, type: "line", indent: 2 },
      { label: "GST/HST Payable", amount: 31180, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 239190, type: "subtotal" },
      { label: "Common Shares", amount: 100000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: 109055, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 209055, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 448245, type: "total" },
    ],
  },
  {
    label: "Mid-Year Balance Sheet",
    period: "Jun 30, 2023",
    company: "fashion-house",
    theme: "Half-Year",
    summary:
      "Mid-year balance sheet position. Working capital strong from wholesale collections; inventory peaking ahead of Q3 production for Fall/Winter season.",
    totalAssets: 1292300,
    totalLiabilities: 350800,
    totalEquity: 941500,
    currentRatio: 4.21,
    debtToEquity: 0.37,
    workingCapital: 789000,
    roe: 0.123,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Current Assets", amount: null, type: "subheader" },
      { label: "Cash", amount: 248600, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 384200, type: "line", indent: 2 },
      { label: "Raw Materials Inventory", amount: 168400, type: "line", indent: 2 },
      { label: "Finished Goods Inventory", amount: 224600, type: "line", indent: 2 },
      { label: "Prepaid Insurance", amount: 9000, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 1034800, type: "subtotal", indent: 1 },
      { label: "Property & Equipment, net", amount: 190000, type: "line", indent: 1 },
      { label: "Intangible Assets, net", amount: 67500, type: "line", indent: 1 },
      { label: "TOTAL ASSETS", amount: 1292300, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 245800, type: "line", indent: 2 },
      { label: "Total Current Liabilities", amount: 245800, type: "subtotal", indent: 1 },
      { label: "Notes Payable", amount: 105000, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 350800, type: "subtotal" },
      { label: "Common Shares", amount: 600000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: 341500, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 941500, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 1292300, type: "total" },
    ],
  },
  {
    label: "Year-End Balance Sheet",
    period: "Dec 31, 2023",
    company: "fashion-house",
    theme: "Year-End",
    summary:
      "FY23 year-end balance sheet. Larger AR balance from wholesale shipments through Q4; equipment additions for production expansion; equity grew through retained earnings.",
    totalAssets: 1604200,
    totalLiabilities: 459160,
    totalEquity: 1145040,
    currentRatio: 2.81,
    debtToEquity: 0.4,
    workingCapital: 818670,
    roe: 0.278,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Current Assets", amount: null, type: "subheader" },
      { label: "Cash", amount: 312800, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 624000, type: "line", indent: 2 },
      { label: "Inventory, Combined", amount: 318400, type: "line", indent: 2 },
      { label: "Prepaid Expenses", amount: 5500, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 1260700, type: "subtotal", indent: 1 },
      { label: "Property & Equipment, net", amount: 282000, type: "line", indent: 1 },
      { label: "Intangible Assets, net", amount: 61500, type: "line", indent: 1 },
      { label: "TOTAL ASSETS", amount: 1604200, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 312400, type: "line", indent: 2 },
      { label: "Salaries Payable", amount: 24800, type: "line", indent: 2 },
      { label: "Income Tax Payable", amount: 36960, type: "line", indent: 2 },
      { label: "Total Current Liabilities", amount: 442030, type: "subtotal", indent: 1 },
      { label: "Notes Payable", amount: 90000, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 459160, type: "subtotal" },
      { label: "Common Shares", amount: 600000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: 545040, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 1145040, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 1604200, type: "total" },
    ],
  },
  {
    label: "Foodservice Year-End BS",
    period: "Dec 31, 2023",
    company: "foodservice",
    theme: "Year-End",
    summary:
      "Foodservice year-end balance sheet. Higher equipment base after leasehold improvements; multi-jurisdiction tax payables; working capital tight due to payroll-driven cycle.",
    totalAssets: 497320,
    totalLiabilities: 377300,
    totalEquity: 120020,
    currentRatio: 0.64,
    debtToEquity: 3.14,
    workingCapital: -135100,
    roe: 0.266,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Cash", amount: 124200, type: "line", indent: 2 },
      { label: "Petty Cash", amount: 2000, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 38400, type: "line", indent: 2 },
      { label: "Inventory", amount: 42600, type: "line", indent: 2 },
      { label: "Other Current", amount: 35000, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 242200, type: "subtotal", indent: 1 },
      { label: "Equipment & Smallwares, net", amount: 186000, type: "line", indent: 1 },
      { label: "Leasehold Improvements, net", amount: 69120, type: "line", indent: 1 },
      { label: "TOTAL ASSETS", amount: 497320, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 184800, type: "line", indent: 2 },
      { label: "Accrued Liabilities", amount: 42600, type: "line", indent: 2 },
      { label: "Tax Payables, multi-jurisdiction", amount: 125080, type: "line", indent: 2 },
      { label: "Source Deductions Payable", amount: 24820, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 377300, type: "subtotal" },
      { label: "Common Shares", amount: 200000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: -79980, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 120020, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 497320, type: "total" },
    ],
  },
  {
    label: "Direct Sales Year-End BS",
    period: "Dec 31, 2023",
    company: "direct-sales",
    theme: "Year-End",
    summary:
      "Direct sales year-end balance sheet. Receivables aging well-managed via doubtful accounts allowance; equity strong on retained earnings growth.",
    totalAssets: 840540,
    totalLiabilities: 491400,
    totalEquity: 349140,
    currentRatio: 1.59,
    debtToEquity: 1.41,
    workingCapital: 290200,
    roe: 0.758,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Cash", amount: 198400, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 412800, type: "line", indent: 2 },
      { label: "Less: Allowance for Doubtful Accts", amount: -12400, type: "line", indent: 2 },
      { label: "Inventory", amount: 168000, type: "line", indent: 2 },
      { label: "Prepaid Expenses", amount: 14800, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 781600, type: "subtotal", indent: 1 },
      { label: "Office Equipment, net", amount: 58940, type: "line", indent: 1 },
      { label: "TOTAL ASSETS", amount: 840540, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 298400, type: "line", indent: 2 },
      { label: "Accrued Liabilities", amount: 48600, type: "line", indent: 2 },
      { label: "Commissions Payable", amount: 28400, type: "line", indent: 2 },
      { label: "Tax Payables", amount: 116000, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 491400, type: "subtotal" },
      { label: "Common Shares", amount: 100000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: 249140, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 349140, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 840540, type: "total" },
    ],
  },
  {
    label: "Quarter Balance Sheet",
    period: "Sep 30, 2023",
    company: "fashion-house",
    theme: "Quarterly",
    summary:
      "Q3 2023 balance sheet position. Finished goods inventory peaked ahead of holiday season; cash drawn down on production spend; AR building from wholesale orders.",
    totalAssets: 1453400,
    totalLiabilities: 434300,
    totalEquity: 1019100,
    currentRatio: 3.58,
    debtToEquity: 0.43,
    workingCapital: 870350,
    roe: 0.208,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Cash", amount: 296800, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 412600, type: "line", indent: 2 },
      { label: "Raw Materials Inventory", amount: 142800, type: "line", indent: 2 },
      { label: "Finished Goods Inventory", amount: 348200, type: "line", indent: 2 },
      { label: "Prepaid Insurance", amount: 6750, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 1207150, type: "subtotal", indent: 1 },
      { label: "Property & Equipment, net", amount: 182500, type: "line", indent: 1 },
      { label: "Intangible Assets, net", amount: 63750, type: "line", indent: 1 },
      { label: "TOTAL ASSETS", amount: 1453400, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 318400, type: "line", indent: 2 },
      { label: "Salaries Payable", amount: 18400, type: "line", indent: 2 },
      { label: "Total Current Liabilities", amount: 336800, type: "subtotal", indent: 1 },
      { label: "Notes Payable", amount: 97500, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 434300, type: "subtotal" },
      { label: "Common Shares", amount: 600000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: 419100, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 1019100, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 1453400, type: "total" },
    ],
  },
  {
    label: "Merchandising Case Study",
    period: "Practice Set",
    company: "fashion-house",
    theme: "Case Study",
    summary:
      "Balance sheet prepared for an intermediate accounting case study. Classified balance sheet format with current and non-current sections distinguished.",
    totalAssets: 300380,
    totalLiabilities: 98600,
    totalEquity: 201780,
    currentRatio: 3.62,
    debtToEquity: 0.49,
    workingCapital: 193180,
    roe: 0.371,
    lines: [
      { label: "ASSETS", amount: null, type: "header" },
      { label: "Cash", amount: 48200, type: "line", indent: 2 },
      { label: "Accounts Receivable", amount: 92400, type: "line", indent: 2 },
      { label: "Less: Allowance for Doubtful Accts", amount: -4620, type: "line", indent: 2 },
      { label: "Merchandise Inventory", amount: 124800, type: "line", indent: 2 },
      { label: "Office Supplies", amount: 2400, type: "line", indent: 2 },
      { label: "Prepaid Insurance", amount: 3600, type: "line", indent: 2 },
      { label: "Total Current Assets", amount: 266780, type: "subtotal", indent: 1 },
      { label: "Office Equipment", amount: 48000, type: "line", indent: 2 },
      { label: "Less: Accumulated Depreciation", amount: -14400, type: "line", indent: 2 },
      { label: "Office Equipment, net", amount: 33600, type: "subtotal", indent: 1 },
      { label: "TOTAL ASSETS", amount: 300380, type: "total" },
      { label: "LIABILITIES", amount: null, type: "header" },
      { label: "Accounts Payable", amount: 62800, type: "line", indent: 2 },
      { label: "Salaries Payable", amount: 4800, type: "line", indent: 2 },
      { label: "Unearned Revenue", amount: 6000, type: "line", indent: 2 },
      { label: "Total Current Liabilities", amount: 73600, type: "subtotal", indent: 1 },
      { label: "Notes Payable", amount: 25000, type: "line", indent: 2 },
      { label: "TOTAL LIABILITIES", amount: 98600, type: "subtotal" },
      { label: "Common Shares", amount: 80000, type: "line", indent: 2 },
      { label: "Retained Earnings", amount: 121780, type: "line", indent: 2 },
      { label: "TOTAL EQUITY", amount: 201780, type: "subtotal" },
      { label: "TOTAL LIABILITIES & EQUITY", amount: 300380, type: "total" },
    ],
  },
];
