import { Company } from "./work-samples";

export type ISLine = {
  label: string;
  amount: number | null;
  type: "header" | "line" | "subtotal" | "total" | "spacer";
  indent?: 0 | 1 | 2;
};

export type IncomeStatementVariant = {
  label: string;
  period: string;
  company: Company;
  theme: string;
  summary: string;
  revenue: number;
  netIncome: number;
  netMargin: number;
  grossProfit?: number;
  lines: ISLine[];
};

export const INCOME_STATEMENT_VARIANTS: IncomeStatementVariant[] = [
  {
    label: "Annual Income Statement",
    period: "FY 2022",
    company: "fashion-house",
    theme: "Year-End",
    summary:
      "Full-year income statement for FY22. Revenue split across wholesale, retail boutique and licensing channels. Net margin of 15.4% after 25% corporate tax provision.",
    revenue: 1800000,
    netIncome: 276675,
    netMargin: 0.154,
    grossProfit: 1142000,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Wholesale Revenue", amount: 980000, type: "line", indent: 1 },
      { label: "Retail Boutique Revenue", amount: 760000, type: "line", indent: 1 },
      { label: "Licensing & Royalty Income", amount: 60000, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 1800000, type: "subtotal" },
      { label: "COST OF GOODS SOLD", amount: null, type: "header" },
      { label: "Cost of Goods Sold", amount: -658000, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 1142000, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Design & Sample Development", amount: -110000, type: "line", indent: 1 },
      { label: "Fashion Show & Runway", amount: -75000, type: "line", indent: 1 },
      { label: "Salaries & Wages", amount: -290000, type: "line", indent: 1 },
      { label: "Rent", amount: -96000, type: "line", indent: 1 },
      { label: "Utilities", amount: -19000, type: "line", indent: 1 },
      { label: "Advertising & Marketing", amount: -88000, type: "line", indent: 1 },
      { label: "Shipping & Freight", amount: -24000, type: "line", indent: 1 },
      { label: "Depreciation", amount: -30000, type: "line", indent: 1 },
      { label: "Amortization", amount: -15000, type: "line", indent: 1 },
      { label: "Insurance", amount: -16500, type: "line", indent: 1 },
      { label: "Total Operating Expenses", amount: -763500, type: "subtotal" },
      { label: "Operating Income (EBIT)", amount: 378500, type: "subtotal" },
      { label: "Interest Expense", amount: -9600, type: "line", indent: 1 },
      { label: "Income Before Income Tax", amount: 368900, type: "subtotal" },
      { label: "Income Tax Expense (25%)", amount: -92225, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 276675, type: "total" },
    ],
  },
  {
    label: "Q1 Income Statement",
    period: "Q1 2024",
    company: "fashion-house",
    theme: "Quarterly",
    summary:
      "Q1 2024 quarterly income statement. Strong wholesale orders shipped in January and February, retail picking up in March with new spring collection launch.",
    revenue: 398240,
    netIncome: 47800,
    netMargin: 0.12,
    grossProfit: 246240,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Wholesale Revenue", amount: 218400, type: "line", indent: 1 },
      { label: "Retail Revenue", amount: 174600, type: "line", indent: 1 },
      { label: "Foreign Exchange Gain", amount: 5240, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 398240, type: "subtotal" },
      { label: "COST OF GOODS SOLD", amount: null, type: "header" },
      { label: "COGS", amount: -152000, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 246240, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Salaries & Wages", amount: -67200, type: "line", indent: 1 },
      { label: "Rent", amount: -24000, type: "line", indent: 1 },
      { label: "Marketing", amount: -28400, type: "line", indent: 1 },
      { label: "Utilities", amount: -4800, type: "line", indent: 1 },
      { label: "Depreciation", amount: -7500, type: "line", indent: 1 },
      { label: "Other Operating", amount: -18475, type: "line", indent: 1 },
      { label: "Operating Income", amount: 95865, type: "subtotal" },
      { label: "Income Tax (25%)", amount: -23966, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 71899, type: "total" },
    ],
  },
  {
    label: "Foodservice Q1",
    period: "Q1 2024",
    company: "foodservice",
    theme: "Quarterly",
    summary:
      "Foodservice operator Q1 income statement. Revenue from F&B sales and catering. Heavy variable labour and food cost structure; modest operating margin.",
    revenue: 297950,
    netIncome: 18400,
    netMargin: 0.062,
    grossProfit: 208750,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Food & Beverage Revenue", amount: 281550, type: "line", indent: 1 },
      { label: "Catering Revenue", amount: 16400, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 297950, type: "subtotal" },
      { label: "COST OF GOODS SOLD", amount: null, type: "header" },
      { label: "F&B COGS", amount: -89200, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 208750, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Salaries & Wages", amount: -145800, type: "line", indent: 1 },
      { label: "Employer Payroll Taxes", amount: -11420, type: "line", indent: 1 },
      { label: "Benefits", amount: -4200, type: "line", indent: 1 },
      { label: "Rent", amount: -22400, type: "line", indent: 1 },
      { label: "Utilities", amount: -3680, type: "line", indent: 1 },
      { label: "Cleaning Supplies", amount: -4200, type: "line", indent: 1 },
      { label: "Bank Charges", amount: -485, type: "line", indent: 1 },
      { label: "Depreciation", amount: -2500, type: "line", indent: 1 },
      { label: "Operating Income", amount: 14065, type: "subtotal" },
      { label: "Income Tax", amount: -4135, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 9930, type: "total" },
    ],
  },
  {
    label: "Direct Sales Q1",
    period: "Q1 2024",
    company: "direct-sales",
    theme: "Quarterly",
    summary:
      "Direct-sales operation Q1 income statement. Multi-channel revenue (wholesale, retail, online). Sales commission expense and bad debt provision are material lines.",
    revenue: 377110,
    netIncome: 36200,
    netMargin: 0.096,
    grossProfit: 234310,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Wholesale Revenue", amount: 198400, type: "line", indent: 1 },
      { label: "Retail Revenue", amount: 156200, type: "line", indent: 1 },
      { label: "Online Revenue", amount: 22510, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 377110, type: "subtotal" },
      { label: "COST OF GOODS SOLD", amount: null, type: "header" },
      { label: "COGS", amount: -142800, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 234310, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Sales Commissions", amount: -36400, type: "line", indent: 1 },
      { label: "Salaries & Wages", amount: -84200, type: "line", indent: 1 },
      { label: "Advertising", amount: -22400, type: "line", indent: 1 },
      { label: "Rent", amount: -12000, type: "line", indent: 1 },
      { label: "Travel & Entertainment", amount: -8400, type: "line", indent: 1 },
      { label: "Bad Debt Expense", amount: -4920, type: "line", indent: 1 },
      { label: "Bank Charges", amount: -285, type: "line", indent: 1 },
      { label: "Depreciation", amount: -2100, type: "line", indent: 1 },
      { label: "Telephone", amount: -1240, type: "line", indent: 1 },
      { label: "Operating Income", amount: 62365, type: "subtotal" },
      { label: "Income Tax (25%)", amount: -15591, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 46774, type: "total" },
    ],
  },
  {
    label: "Annual Income Statement",
    period: "FY 2023",
    company: "fashion-house",
    theme: "Year-End",
    summary:
      "FY23 annual income statement. Revenue growth of 22% over FY22 driven by retail expansion and new licensing partnerships. Margin held flat as input costs rose.",
    revenue: 2196000,
    netIncome: 318420,
    netMargin: 0.145,
    grossProfit: 1393880,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Wholesale Revenue", amount: 1188000, type: "line", indent: 1 },
      { label: "Retail Revenue", amount: 928000, type: "line", indent: 1 },
      { label: "Licensing & Royalties", amount: 80000, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 2196000, type: "subtotal" },
      { label: "COGS", amount: -802120, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 1393880, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Salaries & Wages", amount: -358000, type: "line", indent: 1 },
      { label: "Marketing", amount: -118000, type: "line", indent: 1 },
      { label: "Rent", amount: -96000, type: "line", indent: 1 },
      { label: "Design & Sampling", amount: -142000, type: "line", indent: 1 },
      { label: "Other Operating", amount: -159000, type: "line", indent: 1 },
      { label: "Depreciation & Amortization", amount: -52500, type: "line", indent: 1 },
      { label: "Operating Income", amount: 468380, type: "subtotal" },
      { label: "Interest Expense", amount: -7200, type: "line", indent: 1 },
      { label: "Income Tax (25%)", amount: -115295, type: "line", indent: 1 },
      { label: "Foreign Exchange Loss", amount: -27465, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 318420, type: "total" },
    ],
  },
  {
    label: "March Monthly IS",
    period: "March 2024",
    company: "fashion-house",
    theme: "Monthly",
    summary:
      "Monthly income statement for March 2024 produced as part of monthly management reporting. Includes month-end accruals and FX revaluation impacts.",
    revenue: 138420,
    netIncome: 18600,
    netMargin: 0.134,
    grossProfit: 82420,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Wholesale Revenue", amount: 78400, type: "line", indent: 1 },
      { label: "Retail Revenue", amount: 58420, type: "line", indent: 1 },
      { label: "Foreign Exchange Gain", amount: 1600, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 138420, type: "subtotal" },
      { label: "COGS", amount: -56000, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 82420, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Salaries & Wages", amount: -24800, type: "line", indent: 1 },
      { label: "Rent", amount: -8000, type: "line", indent: 1 },
      { label: "Marketing", amount: -9400, type: "line", indent: 1 },
      { label: "Utilities", amount: -1600, type: "line", indent: 1 },
      { label: "Depreciation", amount: -2500, type: "line", indent: 1 },
      { label: "Other Operating", amount: -6320, type: "line", indent: 1 },
      { label: "Operating Income", amount: 29800, type: "subtotal" },
      { label: "Income Tax", amount: -7450, type: "line", indent: 1 },
      { label: "Bank Charges & Other", amount: -3750, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 18600, type: "total" },
    ],
  },
  {
    label: "Foodservice FY23",
    period: "FY 2023",
    company: "foodservice",
    theme: "Year-End",
    summary:
      "FY23 foodservice income statement. Captures full year revenue from F&B and catering, full payroll cycle, and seasonal variation in margin.",
    revenue: 2675800,
    netIncome: 75520,
    netMargin: 0.028,
    grossProfit: 1933000,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Food & Beverage Revenue", amount: 2475800, type: "line", indent: 1 },
      { label: "Catering Revenue", amount: 200000, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 2675800, type: "subtotal" },
      { label: "F&B COGS", amount: -742800, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 1933000, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Salaries & Wages", amount: -1248000, type: "line", indent: 1 },
      { label: "Employer Payroll Taxes", amount: -86200, type: "line", indent: 1 },
      { label: "Benefits", amount: -48400, type: "line", indent: 1 },
      { label: "Rent", amount: -192000, type: "line", indent: 1 },
      { label: "Utilities", amount: -38400, type: "line", indent: 1 },
      { label: "Cleaning & Maintenance", amount: -43400, type: "line", indent: 1 },
      { label: "Marketing", amount: -38400, type: "line", indent: 1 },
      { label: "Insurance", amount: -14800, type: "line", indent: 1 },
      { label: "Depreciation", amount: -19280, type: "line", indent: 1 },
      { label: "Bank Charges", amount: -4200, type: "line", indent: 1 },
      { label: "Operating Income", amount: 199920, type: "subtotal" },
      { label: "Other Operating", amount: -48880, type: "line", indent: 1 },
      { label: "Income Tax", amount: -75520, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 75520, type: "total" },
    ],
  },
  {
    label: "Direct Sales FY23",
    period: "FY 2023",
    company: "direct-sales",
    theme: "Year-End",
    summary:
      "Direct sales FY23 income statement. Revenue across wholesale, retail and online channels with material commission expense and bad debt reserve increase.",
    revenue: 1735600,
    netIncome: 162400,
    netMargin: 0.094,
    grossProfit: 1037200,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Wholesale Revenue", amount: 884200, type: "line", indent: 1 },
      { label: "Retail Revenue", amount: 642800, type: "line", indent: 1 },
      { label: "Online Revenue", amount: 184200, type: "line", indent: 1 },
      { label: "Other Revenue", amount: 24400, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 1735600, type: "subtotal" },
      { label: "COGS", amount: -698400, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 1037200, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Sales Commissions", amount: -188400, type: "line", indent: 1 },
      { label: "Salaries & Wages", amount: -426800, type: "line", indent: 1 },
      { label: "Advertising", amount: -132400, type: "line", indent: 1 },
      { label: "Rent", amount: -84000, type: "line", indent: 1 },
      { label: "Travel & Entertainment", amount: -42800, type: "line", indent: 1 },
      { label: "Bad Debt Expense", amount: -12400, type: "line", indent: 1 },
      { label: "Depreciation", amount: -12600, type: "line", indent: 1 },
      { label: "Bank Charges", amount: -2900, type: "line", indent: 1 },
      { label: "Other Operating", amount: -19300, type: "line", indent: 1 },
      { label: "Operating Income", amount: 115600, type: "subtotal" },
      { label: "Income Tax", amount: -54200, type: "line", indent: 1 },
      { label: "Other Income, net", amount: 101000, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 162400, type: "total" },
    ],
  },
  {
    label: "Half-Year IS",
    period: "H1 2023",
    company: "fashion-house",
    theme: "Half-Year",
    summary:
      "Half-year income statement for the six months ending June 30, 2023. Strong wholesale season offset by lower retail traffic versus prior year.",
    revenue: 903225,
    netIncome: 114800,
    netMargin: 0.127,
    grossProfit: 523225,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Wholesale Revenue", amount: 542000, type: "line", indent: 1 },
      { label: "Retail Revenue", amount: 361225, type: "line", indent: 1 },
      { label: "Total Revenue", amount: 903225, type: "subtotal" },
      { label: "COGS", amount: -380000, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 523225, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Salaries & Wages", amount: -168000, type: "line", indent: 1 },
      { label: "Rent", amount: -48000, type: "line", indent: 1 },
      { label: "Marketing", amount: -44000, type: "line", indent: 1 },
      { label: "Utilities", amount: -9500, type: "line", indent: 1 },
      { label: "Depreciation & Amortization", amount: -22500, type: "line", indent: 1 },
      { label: "Insurance", amount: -9000, type: "line", indent: 1 },
      { label: "Operating Income", amount: 222225, type: "subtotal" },
      { label: "Interest Expense", amount: -4900, type: "line", indent: 1 },
      { label: "Income Tax (25%)", amount: -54331, type: "line", indent: 1 },
      { label: "Other Operating", amount: -48194, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 114800, type: "total" },
    ],
  },
  {
    label: "Merchandising Case Study",
    period: "Practice Set",
    company: "fashion-house",
    theme: "Case Study",
    summary:
      "Income statement prepared for an intermediate accounting case study. Merchandising operations with sales returns, allowances and freight-out included.",
    revenue: 322780,
    netIncome: 76660,
    netMargin: 0.238,
    grossProfit: 154780,
    lines: [
      { label: "REVENUE", amount: null, type: "header" },
      { label: "Gross Sales", amount: 340000, type: "line", indent: 1 },
      { label: "Less: Sales Returns & Allowances", amount: -12500, type: "line", indent: 1 },
      { label: "Less: Sales Discounts", amount: -4720, type: "line", indent: 1 },
      { label: "Net Sales", amount: 322780, type: "subtotal" },
      { label: "COGS", amount: -168000, type: "line", indent: 1 },
      { label: "Gross Profit", amount: 154780, type: "subtotal" },
      { label: "OPERATING EXPENSES", amount: null, type: "header" },
      { label: "Salaries Expense", amount: -48000, type: "line", indent: 1 },
      { label: "Rent Expense", amount: -12000, type: "line", indent: 1 },
      { label: "Supplies Expense", amount: -3600, type: "line", indent: 1 },
      { label: "Insurance Expense", amount: -1200, type: "line", indent: 1 },
      { label: "Bad Debt Expense", amount: -4620, type: "line", indent: 1 },
      { label: "Depreciation Expense", amount: -7200, type: "line", indent: 1 },
      { label: "Operating Income", amount: 78160, type: "subtotal" },
      { label: "Interest Expense", amount: -1500, type: "line", indent: 1 },
      { label: "NET INCOME", amount: 76660, type: "total" },
    ],
  },
];
