import { Company } from "./work-samples";

export type JournalRow = {
  date: string;
  je: string;
  account: string;
  desc: string;
  debit: number;
  credit: number;
};

export type JournalVariant = {
  label: string;
  period: string;
  company: Company;
  theme: string;
  summary: string;
  totalDebits: number;
  totalCredits: number;
  entryCount: number;
  rows: JournalRow[];
  showingExcerpt?: boolean;
};

export const JOURNAL_VARIANTS: JournalVariant[] = [
  {
    label: "Annual Journal",
    period: "FY 2022",
    company: "fashion-house",
    theme: "Year-End",
    summary:
      "Full-year journal covering capital raise, inventory build, production, wholesale and retail sales, operating expenses and year-end adjusting entries. 28 entries posted across 19 GL accounts.",
    totalDebits: 6281325,
    totalCredits: 6281325,
    entryCount: 28,
    showingExcerpt: true,
    rows: [
      { date: "Jan 02", je: "J-01", account: "Cash", desc: "Issued common shares to founders to capitalize the business", debit: 600000, credit: 0 },
      { date: "", je: "", account: "    Common Shares", desc: "", debit: 0, credit: 600000 },
      { date: "Jan 04", je: "J-02", account: "Studio & Showroom Equipment", desc: "Bought equipment, part cash, part note", debit: 180000, credit: 0 },
      { date: "", je: "", account: "    Cash", desc: "", debit: 0, credit: 60000 },
      { date: "", je: "", account: "    Notes Payable", desc: "", debit: 0, credit: 120000 },
      { date: "Feb 01", je: "J-05", account: "Raw Materials Inventory", desc: "Purchased fabrics on account", debit: 620000, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable", desc: "", debit: 0, credit: 620000 },
      { date: "Mar 10", je: "J-07", account: "Finished Goods Inventory", desc: "Production run, fabric and labour into garments", debit: 720000, credit: 0 },
      { date: "", je: "", account: "    Raw Materials Inventory", desc: "", debit: 0, credit: 520000 },
      { date: "", je: "", account: "    Cash", desc: "", debit: 0, credit: 200000 },
      { date: "Apr 15", je: "J-09", account: "Accounts Receivable", desc: "Wholesale orders shipped on credit", debit: 980000, credit: 0 },
      { date: "", je: "", account: "    Wholesale Revenue", desc: "", debit: 0, credit: 980000 },
      { date: "May 20", je: "J-11", account: "Cash", desc: "Direct-to-consumer retail sales", debit: 760000, credit: 0 },
      { date: "", je: "", account: "    Retail Boutique Revenue", desc: "", debit: 0, credit: 760000 },
      { date: "Aug 15", je: "J-16", account: "Salaries & Wages Expense", desc: "Paid atelier and retail staff", debit: 268000, credit: 0 },
      { date: "", je: "", account: "    Cash", desc: "", debit: 0, credit: 268000 },
      { date: "Dec 31", je: "J-24", account: "Depreciation Expense", desc: "Adjusting: equipment depreciation", debit: 30000, credit: 0 },
      { date: "", je: "", account: "    Accumulated Depreciation", desc: "", debit: 0, credit: 30000 },
      { date: "Dec 31", je: "J-28", account: "Income Tax Expense", desc: "Adjusting: accrued corporate income tax (25%)", debit: 92225, credit: 0 },
      { date: "", je: "", account: "    Income Tax Payable", desc: "", debit: 0, credit: 92225 },
    ],
  },
  {
    label: "Month-End Close",
    period: "March 2024",
    company: "fashion-house",
    theme: "Month-End",
    summary:
      "Standard month-end accruals, deferrals, depreciation and reclasses. All accruals flagged for reversal on the first day of April.",
    totalDebits: 59745,
    totalCredits: 59745,
    entryCount: 8,
    rows: [
      { date: "Mar 31", je: "ME-01", account: "Raw Materials Inventory", desc: "Accrue unbilled fabric received not invoiced", debit: 18400, credit: 0 },
      { date: "", je: "", account: "    Accrued Liabilities", desc: "", debit: 0, credit: 18400 },
      { date: "Mar 31", je: "ME-02", account: "Depreciation Expense", desc: "Studio & showroom equipment", debit: 2500, credit: 0 },
      { date: "", je: "", account: "    Accumulated Depreciation", desc: "", debit: 0, credit: 2500 },
      { date: "Mar 31", je: "ME-03", account: "Amortization Expense", desc: "Brand & design intangibles", debit: 1250, credit: 0 },
      { date: "", je: "", account: "    Accumulated Amortization", desc: "", debit: 0, credit: 1250 },
      { date: "Mar 31", je: "ME-04", account: "Insurance Expense", desc: "Prepaid insurance expired", debit: 1375, credit: 0 },
      { date: "", je: "", account: "    Prepaid Insurance", desc: "", debit: 0, credit: 1375 },
      { date: "Mar 31", je: "ME-05", account: "Salaries & Wages Expense", desc: "Accrue payroll earned, not yet paid", debit: 16800, credit: 0 },
      { date: "", je: "", account: "    Salaries Payable", desc: "", debit: 0, credit: 16800 },
      { date: "Mar 31", je: "ME-06", account: "Accounts Payable", desc: "FX gain on USD wire revaluation", debit: 640, credit: 0 },
      { date: "", je: "", account: "    Foreign Exchange Gain", desc: "", debit: 0, credit: 640 },
      { date: "Mar 31", je: "ME-07", account: "Rent Expense", desc: "Reclass rent miscoded to office supplies", debit: 9600, credit: 0 },
      { date: "", je: "", account: "    Office Supplies Expense", desc: "", debit: 0, credit: 9600 },
      { date: "Mar 31", je: "ME-08", account: "GST/HST Receivable (ITC)", desc: "Accrue GST/HST payable for the period", debit: 4820, credit: 0 },
      { date: "", je: "", account: "GST/HST Suspense", desc: "", debit: 4360, credit: 0 },
      { date: "", je: "", account: "    GST/HST Payable", desc: "", debit: 0, credit: 9180 },
    ],
  },
  {
    label: "Payroll Accruals",
    period: "April 2024",
    company: "foodservice",
    theme: "Payroll",
    summary:
      "Bi-weekly payroll accrual, employer source deductions and statutory liabilities. CPP, EI and income tax withholdings posted to separate payable accounts.",
    totalDebits: 124320,
    totalCredits: 124320,
    entryCount: 5,
    rows: [
      { date: "Apr 12", je: "PR-01", account: "Salaries & Wages Expense", desc: "Bi-weekly gross payroll", debit: 84500, credit: 0 },
      { date: "", je: "", account: "    CPP Payable", desc: "", debit: 0, credit: 4480 },
      { date: "", je: "", account: "    EI Payable", desc: "", debit: 0, credit: 1390 },
      { date: "", je: "", account: "    Federal Income Tax Payable", desc: "", debit: 0, credit: 12640 },
      { date: "", je: "", account: "    Salaries Payable", desc: "", debit: 0, credit: 65990 },
      { date: "Apr 12", je: "PR-02", account: "Employer Payroll Taxes Expense", desc: "Employer portion of CPP and EI", debit: 6420, credit: 0 },
      { date: "", je: "", account: "    CPP Payable", desc: "", debit: 0, credit: 4480 },
      { date: "", je: "", account: "    EI Payable", desc: "", debit: 0, credit: 1940 },
      { date: "Apr 12", je: "PR-03", account: "Benefits Expense", desc: "Group health and dental premium", debit: 4200, credit: 0 },
      { date: "", je: "", account: "    Benefits Payable", desc: "", debit: 0, credit: 4200 },
      { date: "Apr 26", je: "PR-04", account: "Salaries & Wages Expense", desc: "Second bi-weekly run", debit: 26800, credit: 0 },
      { date: "", je: "", account: "    Salaries Payable", desc: "", debit: 0, credit: 26800 },
      { date: "Apr 30", je: "PR-05", account: "Salaries Payable", desc: "Direct deposit settlement", debit: 2400, credit: 0 },
      { date: "", je: "", account: "    Cash, RBC Operating", desc: "", debit: 0, credit: 2400 },
    ],
  },
  {
    label: "AR Cash Application",
    period: "March 2024",
    company: "direct-sales",
    theme: "Accounts Receivable",
    summary:
      "Customer remittances received and applied to the AR sub-ledger. Partial payments leave balance open, unapplied credits cleared on next invoice.",
    totalDebits: 124756.25,
    totalCredits: 124756.25,
    entryCount: 7,
    rows: [
      { date: "Mar 04", je: "AR-01", account: "Cash, RBC Operating", desc: "Receipt RCT-5510 from Maple Leaf Retail", debit: 12400, credit: 0 },
      { date: "", je: "", account: "    Accounts Receivable, SI-9001", desc: "", debit: 0, credit: 12400 },
      { date: "Mar 06", je: "AR-02", account: "Cash, RBC Operating", desc: "Receipt RCT-5511 from Pacific Boutiques", debit: 8650, credit: 0 },
      { date: "", je: "", account: "    Accounts Receivable, SI-9002", desc: "", debit: 0, credit: 8650 },
      { date: "Mar 11", je: "AR-03", account: "Cash, RBC Operating", desc: "Partial payment from Maple Leaf, SI-9007", debit: 15000, credit: 0 },
      { date: "", je: "", account: "    Accounts Receivable, SI-9007", desc: "", debit: 0, credit: 15000 },
      { date: "Mar 12", je: "AR-04", account: "Cash, RBC USD", desc: "Wire from Coastal Department Stores", debit: 22150, credit: 0 },
      { date: "", je: "", account: "    Accounts Receivable, SI-9004", desc: "", debit: 0, credit: 22150 },
      { date: "Mar 27", je: "AR-05", account: "Cash, RBC Operating", desc: "Unapplied credit on Maple Leaf account", debit: 5000, credit: 0 },
      { date: "", je: "", account: "    Customer Deposits", desc: "", debit: 0, credit: 5000 },
      { date: "Mar 29", je: "AR-06", account: "Cash, RBC Operating", desc: "Receipt RCT-5521 from Northern Apparel", debit: 7740, credit: 0 },
      { date: "", je: "", account: "    Accounts Receivable, SI-9012", desc: "", debit: 0, credit: 7740 },
      { date: "Mar 31", je: "AR-07", account: "Cash, RBC Operating", desc: "Various smaller receipts (4 customers)", debit: 53816.25, credit: 0 },
      { date: "", je: "", account: "    Accounts Receivable, various", desc: "", debit: 0, credit: 53816.25 },
    ],
  },
  {
    label: "FX Revaluation",
    period: "Q1 2024",
    company: "fashion-house",
    theme: "Foreign Exchange",
    summary:
      "Period-end revaluation of USD-denominated AP, AR and bank balances at closing CAD/USD spot rate. Unrealized FX gains and losses recognized.",
    totalDebits: 14820,
    totalCredits: 14820,
    entryCount: 4,
    rows: [
      { date: "Mar 31", je: "FX-01", account: "Accounts Payable, USD vendors", desc: "Revalue USD AP at closing rate 1.3520 (from 1.3580)", debit: 4280, credit: 0 },
      { date: "", je: "", account: "    Foreign Exchange Gain", desc: "", debit: 0, credit: 4280 },
      { date: "Mar 31", je: "FX-02", account: "Foreign Exchange Loss", desc: "Revalue USD AR at closing rate", debit: 2150, credit: 0 },
      { date: "", je: "", account: "    Accounts Receivable, USD customers", desc: "", debit: 0, credit: 2150 },
      { date: "Mar 31", je: "FX-03", account: "Cash, RBC USD", desc: "Revalue USD cash balance", debit: 1290, credit: 0 },
      { date: "", je: "", account: "    Foreign Exchange Gain", desc: "", debit: 0, credit: 1290 },
      { date: "Mar 31", je: "FX-04", account: "Foreign Exchange Loss", desc: "Settled USD wire INV-2207, realized loss", debit: 7100, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable, USD vendors", desc: "", debit: 0, credit: 7100 },
    ],
  },
  {
    label: "Depreciation & Amortization",
    period: "Q4 2023",
    company: "fashion-house",
    theme: "Fixed Assets",
    summary:
      "Quarterly depreciation and amortization run across all classes of property and intangible assets. Straight-line method for equipment, accelerated for intangibles.",
    totalDebits: 18750,
    totalCredits: 18750,
    entryCount: 5,
    rows: [
      { date: "Dec 31", je: "DA-01", account: "Depreciation Expense", desc: "Studio & showroom equipment, 10-yr SL", debit: 7500, credit: 0 },
      { date: "", je: "", account: "    Accumulated Depreciation, Equipment", desc: "", debit: 0, credit: 7500 },
      { date: "Dec 31", je: "DA-02", account: "Depreciation Expense", desc: "POS systems & computer hardware, 5-yr SL", debit: 2200, credit: 0 },
      { date: "", je: "", account: "    Accumulated Depreciation, IT", desc: "", debit: 0, credit: 2200 },
      { date: "Dec 31", je: "DA-03", account: "Depreciation Expense", desc: "Leasehold improvements, lease term", debit: 3800, credit: 0 },
      { date: "", je: "", account: "    Accumulated Depreciation, LHI", desc: "", debit: 0, credit: 3800 },
      { date: "Dec 31", je: "DA-04", account: "Amortization Expense", desc: "Brand trademarks, 15-yr SL", debit: 3750, credit: 0 },
      { date: "", je: "", account: "    Accumulated Amortization, Trademarks", desc: "", debit: 0, credit: 3750 },
      { date: "Dec 31", je: "DA-05", account: "Amortization Expense", desc: "Software licenses, 3-yr SL", debit: 1500, credit: 0 },
      { date: "", je: "", account: "    Accumulated Amortization, Software", desc: "", debit: 0, credit: 1500 },
    ],
  },
  {
    label: "Vendor Invoice Posting",
    period: "February 2024",
    company: "foodservice",
    theme: "Accounts Payable",
    summary:
      "Daily vendor invoice posting following three-way match against PO and goods receipt. GST/HST input tax credit captured on each posting.",
    totalDebits: 92840,
    totalCredits: 92840,
    entryCount: 7,
    rows: [
      { date: "Feb 02", je: "AP-01", account: "Food & Beverage COGS", desc: "Sysco invoice INV-44210, weekly delivery", debit: 18600, credit: 0 },
      { date: "", je: "", account: "GST/HST Receivable (ITC)", desc: "", debit: 2418, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable, Sysco", desc: "", debit: 0, credit: 21018 },
      { date: "Feb 06", je: "AP-02", account: "Cleaning Supplies Expense", desc: "Ecolab quarterly chemical order", debit: 4200, credit: 0 },
      { date: "", je: "", account: "GST/HST Receivable (ITC)", desc: "", debit: 546, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable, Ecolab", desc: "", debit: 0, credit: 4746 },
      { date: "Feb 12", je: "AP-03", account: "Repairs & Maintenance", desc: "HVAC service contract, monthly", debit: 1800, credit: 0 },
      { date: "", je: "", account: "GST/HST Receivable (ITC)", desc: "", debit: 234, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable, Cool-Tech HVAC", desc: "", debit: 0, credit: 2034 },
      { date: "Feb 15", je: "AP-04", account: "Food & Beverage COGS", desc: "GFS bi-weekly grocery delivery", debit: 22400, credit: 0 },
      { date: "", je: "", account: "GST/HST Receivable (ITC)", desc: "", debit: 2912, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable, GFS", desc: "", debit: 0, credit: 25312 },
      { date: "Feb 22", je: "AP-05", account: "Utilities Expense", desc: "Hydro and gas combined billing", debit: 3680, credit: 0 },
      { date: "", je: "", account: "GST/HST Receivable (ITC)", desc: "", debit: 478, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable, BC Hydro", desc: "", debit: 0, credit: 4158 },
      { date: "Feb 27", je: "AP-06", account: "Food & Beverage COGS", desc: "Sysco weekly delivery", debit: 31200, credit: 0 },
      { date: "", je: "", account: "GST/HST Receivable (ITC)", desc: "", debit: 4056, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable, Sysco", desc: "", debit: 0, credit: 35256 },
      { date: "Feb 28", je: "AP-07", account: "Office Supplies", desc: "Staples monthly office supplies", debit: 458, credit: 0 },
      { date: "", je: "", account: "GST/HST Receivable (ITC)", desc: "", debit: 58, credit: 0 },
      { date: "", je: "", account: "    Accounts Payable, Staples", desc: "", debit: 0, credit: 516 },
    ],
  },
  {
    label: "Inventory Adjustments",
    period: "Q2 2023",
    company: "fashion-house",
    theme: "Inventory",
    summary:
      "Physical count adjustments, obsolescence write-downs and seasonal markdowns. Inventory variance investigated against perpetual records before posting.",
    totalDebits: 31200,
    totalCredits: 31200,
    entryCount: 5,
    rows: [
      { date: "Jun 30", je: "IA-01", account: "COGS, Inventory Shrink", desc: "Physical count short, raw materials", debit: 8400, credit: 0 },
      { date: "", je: "", account: "    Raw Materials Inventory", desc: "", debit: 0, credit: 8400 },
      { date: "Jun 30", je: "IA-02", account: "COGS, Obsolescence", desc: "Write-down of prior-season finished goods", debit: 12500, credit: 0 },
      { date: "", je: "", account: "    Finished Goods Inventory", desc: "", debit: 0, credit: 12500 },
      { date: "Jun 30", je: "IA-03", account: "Inventory Reserve Expense", desc: "Increase reserve for slow-moving SKUs", debit: 6300, credit: 0 },
      { date: "", je: "", account: "    Allowance for Inventory Obsolescence", desc: "", debit: 0, credit: 6300 },
      { date: "Jun 30", je: "IA-04", account: "Raw Materials Inventory", desc: "Found inventory not on system, fabric roll", debit: 1800, credit: 0 },
      { date: "", je: "", account: "    COGS, Inventory Adjustment", desc: "", debit: 0, credit: 1800 },
      { date: "Jun 30", je: "IA-05", account: "Marketing Expense, Samples", desc: "Reclass sample garments out of inventory", debit: 2200, credit: 0 },
      { date: "", je: "", account: "    Finished Goods Inventory", desc: "", debit: 0, credit: 2200 },
    ],
  },
  {
    label: "Sales Tax Remittance",
    period: "Q1 2024",
    company: "fashion-house",
    theme: "Tax Compliance",
    summary:
      "Quarterly sales tax remittance preparation. GST/HST output tax netted against input tax credits, QST and PST tracked separately by jurisdiction.",
    totalDebits: 86380,
    totalCredits: 86380,
    entryCount: 3,
    rows: [
      { date: "Apr 30", je: "TX-01", account: "GST/HST Payable", desc: "Q1 output tax collected on sales", debit: 127660, credit: 0 },
      { date: "", je: "", account: "    GST/HST Receivable (ITC)", desc: "", debit: 0, credit: 41280 },
      { date: "", je: "", account: "    Cash, RBC Operating", desc: "Net remittance to CRA", debit: 0, credit: 86380 },
      { date: "Apr 30", je: "TX-02", account: "QST Payable", desc: "Q1 Quebec sales tax remittance", debit: 18470, credit: 0 },
      { date: "", je: "", account: "    QST Receivable (ITC)", desc: "", debit: 0, credit: 5840 },
      { date: "", je: "", account: "    Cash, RBC Operating", desc: "Net remittance to Revenu Quebec", debit: 0, credit: 12630 },
      { date: "Apr 30", je: "TX-03", account: "PST Payable", desc: "Q1 BC sales tax remittance", debit: 14130, credit: 0 },
      { date: "", je: "", account: "    Cash, RBC Operating", desc: "Remittance to BC Ministry of Finance", debit: 0, credit: 14130 },
    ],
  },
  {
    label: "Bank Reconciliation Entries",
    period: "March 2024",
    company: "direct-sales",
    theme: "Bank Reconciliation",
    summary:
      "Adjustments arising from monthly bank reconciliation: bank service charges, NSF cheques, interest income, and bank-side errors corrected.",
    totalDebits: 4385,
    totalCredits: 4385,
    entryCount: 5,
    rows: [
      { date: "Mar 31", je: "BR-01", account: "Bank Charges Expense", desc: "Monthly service fees, transaction charges", debit: 285, credit: 0 },
      { date: "", je: "", account: "    Cash, RBC Operating", desc: "", debit: 0, credit: 285 },
      { date: "Mar 31", je: "BR-02", account: "Cash, RBC Operating", desc: "Interest credit on operating account", debit: 142, credit: 0 },
      { date: "", je: "", account: "    Interest Income", desc: "", debit: 0, credit: 142 },
      { date: "Mar 31", je: "BR-03", account: "Accounts Receivable, NSF", desc: "Customer cheque returned NSF, INV SI-9015", debit: 2480, credit: 0 },
      { date: "", je: "", account: "    Cash, RBC Operating", desc: "", debit: 0, credit: 2480 },
      { date: "Mar 31", je: "BR-04", account: "NSF Fee Recovery", desc: "Bank NSF fee, recovered from customer", debit: 45, credit: 0 },
      { date: "", je: "", account: "    Cash, RBC Operating", desc: "", debit: 0, credit: 45 },
      { date: "Mar 31", je: "BR-05", account: "Cash, RBC Operating", desc: "Correct prior-period coding error", debit: 1433, credit: 0 },
      { date: "", je: "", account: "    Suspense Account", desc: "", debit: 0, credit: 1433 },
    ],
  },
];
