import { Company } from "./work-samples";

export type TBRow = {
  account: string;
  type: "Asset" | "Contra-Asset" | "Liability" | "Equity" | "Revenue" | "Expense";
  debit: number;
  credit: number;
};

export type TrialBalanceVariant = {
  label: string;
  period: string;
  company: Company;
  theme: string;
  summary: string;
  totalDebits: number;
  totalCredits: number;
  rows: TBRow[];
};

export const TRIAL_BALANCE_VARIANTS: TrialBalanceVariant[] = [
  {
    label: "Year-End Trial Balance",
    period: "Dec 31, 2022",
    company: "fashion-house",
    theme: "Year-End",
    summary:
      "Full year-end trial balance covering 31 accounts across assets, contra-assets, liabilities, equity, revenue and expenses. Total debits equal total credits at $3,019,225.",
    totalDebits: 3019225,
    totalCredits: 3019225,
    rows: [
      { account: "Cash", type: "Asset", debit: 432400, credit: 0 },
      { account: "Accounts Receivable", type: "Asset", debit: 580000, credit: 0 },
      { account: "Raw Materials Inventory", type: "Asset", debit: 100000, credit: 0 },
      { account: "Finished Goods Inventory", type: "Asset", debit: 62000, credit: 0 },
      { account: "Prepaid Insurance", type: "Asset", debit: 1500, credit: 0 },
      { account: "Studio & Showroom Equipment", type: "Asset", debit: 180000, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 30000 },
      { account: "Intangible Assets, Brand", type: "Asset", debit: 90000, credit: 0 },
      { account: "Accumulated Amortization", type: "Contra-Asset", debit: 0, credit: 15000 },
      { account: "Accounts Payable", type: "Liability", debit: 0, credit: 340000 },
      { account: "Salaries Payable", type: "Liability", debit: 0, credit: 22000 },
      { account: "Income Tax Payable", type: "Liability", debit: 0, credit: 92225 },
      { account: "Notes Payable", type: "Liability", debit: 0, credit: 120000 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 600000 },
      { account: "Dividends", type: "Equity", debit: 50000, credit: 0 },
      { account: "Wholesale Revenue", type: "Revenue", debit: 0, credit: 980000 },
      { account: "Retail Boutique Revenue", type: "Revenue", debit: 0, credit: 760000 },
      { account: "Licensing & Royalty Income", type: "Revenue", debit: 0, credit: 60000 },
      { account: "Cost of Goods Sold", type: "Expense", debit: 658000, credit: 0 },
      { account: "Design & Sample Development", type: "Expense", debit: 110000, credit: 0 },
      { account: "Fashion Show & Runway", type: "Expense", debit: 75000, credit: 0 },
      { account: "Salaries & Wages", type: "Expense", debit: 290000, credit: 0 },
      { account: "Rent", type: "Expense", debit: 96000, credit: 0 },
      { account: "Utilities", type: "Expense", debit: 19000, credit: 0 },
      { account: "Advertising & Marketing", type: "Expense", debit: 88000, credit: 0 },
      { account: "Shipping & Freight", type: "Expense", debit: 24000, credit: 0 },
      { account: "Depreciation", type: "Expense", debit: 30000, credit: 0 },
      { account: "Amortization", type: "Expense", debit: 15000, credit: 0 },
      { account: "Insurance", type: "Expense", debit: 16500, credit: 0 },
      { account: "Interest", type: "Expense", debit: 9600, credit: 0 },
      { account: "Income Tax", type: "Expense", debit: 92225, credit: 0 },
    ],
  },
  {
    label: "Month-End Trial Balance",
    period: "Mar 31, 2024",
    company: "fashion-house",
    theme: "Month-End",
    summary:
      "March month-end trial balance post month-end JE package. New accounts added since FY22: GST/HST receivable and payable, FX gain account, accrued liabilities.",
    totalDebits: 1852560,
    totalCredits: 1852560,
    rows: [
      { account: "Cash, RBC Operating", type: "Asset", debit: 318420, credit: 0 },
      { account: "Cash, RBC USD", type: "Asset", debit: 56820, credit: 0 },
      { account: "Accounts Receivable", type: "Asset", debit: 642000, credit: 0 },
      { account: "Raw Materials Inventory", type: "Asset", debit: 142800, credit: 0 },
      { account: "Finished Goods Inventory", type: "Asset", debit: 88600, credit: 0 },
      { account: "Prepaid Insurance", type: "Asset", debit: 4125, credit: 0 },
      { account: "GST/HST Receivable (ITC)", type: "Asset", debit: 14820, credit: 0 },
      { account: "Studio Equipment", type: "Asset", debit: 235000, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 67500 },
      { account: "Intangible Assets", type: "Asset", debit: 90000, credit: 0 },
      { account: "Accumulated Amortization", type: "Contra-Asset", debit: 0, credit: 33750 },
      { account: "Accounts Payable", type: "Liability", debit: 0, credit: 384200 },
      { account: "Accrued Liabilities", type: "Liability", debit: 0, credit: 46800 },
      { account: "Salaries Payable", type: "Liability", debit: 0, credit: 16800 },
      { account: "GST/HST Payable", type: "Liability", debit: 0, credit: 31180 },
      { account: "Income Tax Payable", type: "Liability", debit: 0, credit: 24850 },
      { account: "Notes Payable", type: "Liability", debit: 0, credit: 90000 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 600000 },
      { account: "Retained Earnings", type: "Equity", debit: 0, credit: 159240 },
      { account: "Wholesale Revenue", type: "Revenue", debit: 0, credit: 218400 },
      { account: "Retail Revenue", type: "Revenue", debit: 0, credit: 174600 },
      { account: "Foreign Exchange Gain", type: "Revenue", debit: 0, credit: 5240 },
      { account: "COGS", type: "Expense", debit: 142800, credit: 0 },
      { account: "Salaries & Wages", type: "Expense", debit: 67200, credit: 0 },
      { account: "Rent", type: "Expense", debit: 24000, credit: 0 },
      { account: "Depreciation", type: "Expense", debit: 7500, credit: 0 },
      { account: "Other Operating", type: "Expense", debit: 18475, credit: 0 },
    ],
  },
  {
    label: "Foodservice Month-End TB",
    period: "Mar 31, 2024",
    company: "foodservice",
    theme: "Month-End",
    summary:
      "Trial balance for a foodservice operator with high COGS turnover, low inventory and material payroll-driven costs. Tax accounts split across federal and provincial.",
    totalDebits: 839600,
    totalCredits: 839600,
    rows: [
      { account: "Cash, RBC Operating", type: "Asset", debit: 184500, credit: 0 },
      { account: "Petty Cash", type: "Asset", debit: 2000, credit: 0 },
      { account: "Accounts Receivable", type: "Asset", debit: 24600, credit: 0 },
      { account: "Food & Beverage Inventory", type: "Asset", debit: 38400, credit: 0 },
      { account: "Prepaid Rent", type: "Asset", debit: 8400, credit: 0 },
      { account: "GST/HST Receivable (ITC)", type: "Asset", debit: 12480, credit: 0 },
      { account: "Smallwares & Equipment", type: "Asset", debit: 168000, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 42000 },
      { account: "Accounts Payable, Trade", type: "Liability", debit: 0, credit: 184800 },
      { account: "Accrued Liabilities", type: "Liability", debit: 0, credit: 28400 },
      { account: "Salaries Payable", type: "Liability", debit: 0, credit: 32400 },
      { account: "Source Deductions Payable", type: "Liability", debit: 0, credit: 18510 },
      { account: "GST/HST Payable", type: "Liability", debit: 0, credit: 22440 },
      { account: "QST Payable", type: "Liability", debit: 0, credit: 9180 },
      { account: "PST Payable, BC", type: "Liability", debit: 0, credit: 3920 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 200000 },
      { account: "Retained Earnings (Deficit)", type: "Equity", debit: 115535, credit: 0 },
      { account: "Food & Beverage Revenue", type: "Revenue", debit: 0, credit: 297950 },
      { account: "Food & Beverage COGS", type: "Expense", debit: 89200, credit: 0 },
      { account: "Salaries & Wages", type: "Expense", debit: 145800, credit: 0 },
      { account: "Employer Payroll Taxes", type: "Expense", debit: 11420, credit: 0 },
      { account: "Benefits", type: "Expense", debit: 4200, credit: 0 },
      { account: "Rent", type: "Expense", debit: 22400, credit: 0 },
      { account: "Utilities", type: "Expense", debit: 3680, credit: 0 },
      { account: "Cleaning Supplies", type: "Expense", debit: 4200, credit: 0 },
      { account: "Repairs & Maintenance", type: "Expense", debit: 1800, credit: 0 },
      { account: "Bank Charges", type: "Expense", debit: 485, credit: 0 },
      { account: "Depreciation", type: "Expense", debit: 2500, credit: 0 },
    ],
  },
  {
    label: "Direct Sales Month-End TB",
    period: "Mar 31, 2024",
    company: "direct-sales",
    theme: "Month-End",
    summary:
      "Trial balance for direct sales operation. Heavy AR position from wholesale customers, multiple revenue streams across channels, and commission expense lines.",
    totalDebits: 786810,
    totalCredits: 786810,
    rows: [
      { account: "Cash, RBC Operating", type: "Asset", debit: 124680, credit: 0 },
      { account: "Accounts Receivable, Trade", type: "Asset", debit: 196340, credit: 0 },
      { account: "Allowance for Doubtful Accounts", type: "Contra-Asset", debit: 0, credit: 4920 },
      { account: "Inventory, Finished Goods", type: "Asset", debit: 84600, credit: 0 },
      { account: "Prepaid Insurance", type: "Asset", debit: 9625, credit: 0 },
      { account: "GST/HST Receivable (ITC)", type: "Asset", debit: 14820, credit: 0 },
      { account: "Office Equipment", type: "Asset", debit: 42000, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 18900 },
      { account: "Accounts Payable, Trade", type: "Liability", debit: 0, credit: 148790 },
      { account: "Accrued Liabilities", type: "Liability", debit: 0, credit: 27600 },
      { account: "Commissions Payable", type: "Liability", debit: 0, credit: 14820 },
      { account: "Salaries Payable", type: "Liability", debit: 0, credit: 16800 },
      { account: "GST/HST Payable", type: "Liability", debit: 0, credit: 31180 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 100000 },
      { account: "Retained Earnings", type: "Equity", debit: 0, credit: 46690 },
      { account: "Wholesale Revenue", type: "Revenue", debit: 0, credit: 198400 },
      { account: "Retail Revenue", type: "Revenue", debit: 0, credit: 156200 },
      { account: "Online Revenue", type: "Revenue", debit: 0, credit: 22510 },
      { account: "COGS", type: "Expense", debit: 142800, credit: 0 },
      { account: "Sales Commissions", type: "Expense", debit: 36400, credit: 0 },
      { account: "Salaries & Wages", type: "Expense", debit: 84200, credit: 0 },
      { account: "Advertising", type: "Expense", debit: 22400, credit: 0 },
      { account: "Rent", type: "Expense", debit: 12000, credit: 0 },
      { account: "Travel & Entertainment", type: "Expense", debit: 8400, credit: 0 },
      { account: "Telephone", type: "Expense", debit: 1240, credit: 0 },
      { account: "Bank Charges", type: "Expense", debit: 285, credit: 0 },
      { account: "Bad Debt Expense", type: "Expense", debit: 4920, credit: 0 },
      { account: "Depreciation", type: "Expense", debit: 2100, credit: 0 },
    ],
  },
  {
    label: "Q1 Trial Balance",
    period: "Mar 31, 2022",
    company: "fashion-house",
    theme: "Quarterly",
    summary:
      "First-quarter trial balance after initial capital raise, equipment acquisition and inventory purchases, before any sales activity. Heavy on assets and AP.",
    totalDebits: 1430000,
    totalCredits: 1430000,
    rows: [
      { account: "Cash", type: "Asset", debit: 332000, credit: 0 },
      { account: "Raw Materials Inventory", type: "Asset", debit: 620000, credit: 0 },
      { account: "Prepaid Insurance", type: "Asset", debit: 18000, credit: 0 },
      { account: "Studio Equipment", type: "Asset", debit: 180000, credit: 0 },
      { account: "Intangible Assets", type: "Asset", debit: 90000, credit: 0 },
      { account: "Design & Sample Development", type: "Expense", debit: 64000, credit: 0 },
      { account: "Fashion Show & Runway", type: "Expense", debit: 75000, credit: 0 },
      { account: "Production WIP", type: "Asset", debit: 51000, credit: 0 },
      { account: "Accounts Payable", type: "Liability", debit: 0, credit: 620000 },
      { account: "Notes Payable", type: "Liability", debit: 0, credit: 120000 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 600000 },
      { account: "Wholesale Revenue", type: "Revenue", debit: 0, credit: 90000 },
    ],
  },
  {
    label: "Mid-Year Trial Balance",
    period: "Jun 30, 2023",
    company: "fashion-house",
    theme: "Half-Year",
    summary:
      "Mid-year trial balance for FY23 after first half of operations. Reflects inventory build-up for Fall/Winter collection and Spring/Summer wholesale shipments.",
    totalDebits: 2045700,
    totalCredits: 2045700,
    rows: [
      { account: "Cash", type: "Asset", debit: 248600, credit: 0 },
      { account: "Accounts Receivable", type: "Asset", debit: 384200, credit: 0 },
      { account: "Raw Materials Inventory", type: "Asset", debit: 168400, credit: 0 },
      { account: "Finished Goods Inventory", type: "Asset", debit: 224600, credit: 0 },
      { account: "Prepaid Insurance", type: "Asset", debit: 9000, credit: 0 },
      { account: "Studio Equipment", type: "Asset", debit: 235000, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 45000 },
      { account: "Intangible Assets", type: "Asset", debit: 90000, credit: 0 },
      { account: "Accumulated Amortization", type: "Contra-Asset", debit: 0, credit: 22500 },
      { account: "Accounts Payable", type: "Liability", debit: 0, credit: 245800 },
      { account: "Notes Payable", type: "Liability", debit: 0, credit: 105000 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 600000 },
      { account: "Retained Earnings", type: "Equity", debit: 0, credit: 124175 },
      { account: "Wholesale Revenue", type: "Revenue", debit: 0, credit: 542000 },
      { account: "Retail Revenue", type: "Revenue", debit: 0, credit: 361225 },
      { account: "COGS", type: "Expense", debit: 380000, credit: 0 },
      { account: "Salaries & Wages", type: "Expense", debit: 168000, credit: 0 },
      { account: "Rent", type: "Expense", debit: 48000, credit: 0 },
      { account: "Marketing", type: "Expense", debit: 44000, credit: 0 },
      { account: "Utilities", type: "Expense", debit: 9500, credit: 0 },
      { account: "Depreciation", type: "Expense", debit: 15000, credit: 0 },
      { account: "Amortization", type: "Expense", debit: 7500, credit: 0 },
      { account: "Insurance", type: "Expense", debit: 9000, credit: 0 },
      { account: "Interest", type: "Expense", debit: 4900, credit: 0 },
    ],
  },
  {
    label: "Year-End Trial Balance",
    period: "Dec 31, 2023",
    company: "direct-sales",
    theme: "Year-End",
    summary:
      "FY23 year-end trial balance after full close, adjusting entries posted. Captured growth over prior year with higher AR, expanded inventory and updated reserves.",
    totalDebits: 2573100,
    totalCredits: 2573100,
    rows: [
      { account: "Cash", type: "Asset", debit: 198400, credit: 0 },
      { account: "Accounts Receivable", type: "Asset", debit: 412800, credit: 0 },
      { account: "Allowance for Doubtful Accounts", type: "Contra-Asset", debit: 0, credit: 12400 },
      { account: "Inventory", type: "Asset", debit: 168000, credit: 0 },
      { account: "Prepaid Expenses", type: "Asset", debit: 14800, credit: 0 },
      { account: "Office Equipment", type: "Asset", debit: 84200, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 25260 },
      { account: "Accounts Payable", type: "Liability", debit: 0, credit: 298400 },
      { account: "Accrued Liabilities", type: "Liability", debit: 0, credit: 48600 },
      { account: "Commissions Payable", type: "Liability", debit: 0, credit: 28400 },
      { account: "GST/HST Payable", type: "Liability", debit: 0, credit: 61800 },
      { account: "Income Tax Payable", type: "Liability", debit: 0, credit: 54200 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 100000 },
      { account: "Retained Earnings", type: "Equity", debit: 0, credit: 208440 },
      { account: "Dividends", type: "Equity", debit: 40000, credit: 0 },
      { account: "Wholesale Revenue", type: "Revenue", debit: 0, credit: 884200 },
      { account: "Retail Revenue", type: "Revenue", debit: 0, credit: 642800 },
      { account: "Online Revenue", type: "Revenue", debit: 0, credit: 184200 },
      { account: "Other Revenue", type: "Revenue", debit: 0, credit: 24400 },
      { account: "COGS", type: "Expense", debit: 698400, credit: 0 },
      { account: "Sales Commissions", type: "Expense", debit: 188400, credit: 0 },
      { account: "Salaries & Wages", type: "Expense", debit: 426800, credit: 0 },
      { account: "Advertising", type: "Expense", debit: 132400, credit: 0 },
      { account: "Rent", type: "Expense", debit: 84000, credit: 0 },
      { account: "Travel & Entertainment", type: "Expense", debit: 42800, credit: 0 },
      { account: "Bad Debt Expense", type: "Expense", debit: 12400, credit: 0 },
      { account: "Depreciation", type: "Expense", debit: 12600, credit: 0 },
      { account: "Bank Charges", type: "Expense", debit: 2900, credit: 0 },
      { account: "Income Tax", type: "Expense", debit: 54200, credit: 0 },
    ],
  },
  {
    label: "Foodservice Year-End TB",
    period: "Dec 31, 2023",
    company: "foodservice",
    theme: "Year-End",
    summary:
      "FY23 foodservice operator year-end trial balance with high-volume revenue, payroll-heavy expense structure and multi-jurisdiction sales tax balances.",
    totalDebits: 3332380,
    totalCredits: 3332380,
    rows: [
      { account: "Cash", type: "Asset", debit: 124200, credit: 0 },
      { account: "Petty Cash", type: "Asset", debit: 2000, credit: 0 },
      { account: "Accounts Receivable", type: "Asset", debit: 38400, credit: 0 },
      { account: "Food & Beverage Inventory", type: "Asset", debit: 42600, credit: 0 },
      { account: "Smallwares & Equipment", type: "Asset", debit: 248000, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 62000 },
      { account: "Leasehold Improvements", type: "Asset", debit: 86400, credit: 0 },
      { account: "Accumulated Depreciation, LHI", type: "Contra-Asset", debit: 0, credit: 17280 },
      { account: "Accounts Payable", type: "Liability", debit: 0, credit: 184800 },
      { account: "Accrued Liabilities", type: "Liability", debit: 0, credit: 42600 },
      { account: "GST/HST Payable", type: "Liability", debit: 0, credit: 84200 },
      { account: "QST Payable", type: "Liability", debit: 0, credit: 28400 },
      { account: "PST Payable", type: "Liability", debit: 0, credit: 12480 },
      { account: "Source Deductions Payable", type: "Liability", debit: 0, credit: 24820 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 200000 },
      { account: "Retained Earnings (Deficit)", type: "Equity", debit: 239380, credit: 0 },
      { account: "Food & Beverage Revenue", type: "Revenue", debit: 0, credit: 2475800 },
      { account: "Catering Revenue", type: "Revenue", debit: 0, credit: 200000 },
      { account: "F&B COGS", type: "Expense", debit: 742800, credit: 0 },
      { account: "Salaries & Wages", type: "Expense", debit: 1248000, credit: 0 },
      { account: "Employer Payroll Taxes", type: "Expense", debit: 86200, credit: 0 },
      { account: "Benefits", type: "Expense", debit: 48400, credit: 0 },
      { account: "Rent", type: "Expense", debit: 192000, credit: 0 },
      { account: "Utilities", type: "Expense", debit: 38400, credit: 0 },
      { account: "Cleaning Supplies", type: "Expense", debit: 18600, credit: 0 },
      { account: "Repairs & Maintenance", type: "Expense", debit: 24800, credit: 0 },
      { account: "Marketing", type: "Expense", debit: 38400, credit: 0 },
      { account: "Insurance", type: "Expense", debit: 14800, credit: 0 },
      { account: "Bank Charges", type: "Expense", debit: 4200, credit: 0 },
      { account: "Depreciation", type: "Expense", debit: 19280, credit: 0 },
      { account: "Income Tax", type: "Expense", debit: 75520, credit: 0 },
    ],
  },
  {
    label: "Quarter Trial Balance",
    period: "Sep 30, 2023",
    company: "fashion-house",
    theme: "Quarterly",
    summary:
      "Q3 2023 trial balance reflecting Fall/Winter collection production cycle. Note increased finished goods inventory ahead of holiday selling season.",
    totalDebits: 2474150,
    totalCredits: 2474150,
    rows: [
      { account: "Cash", type: "Asset", debit: 296800, credit: 0 },
      { account: "Accounts Receivable", type: "Asset", debit: 412600, credit: 0 },
      { account: "Raw Materials Inventory", type: "Asset", debit: 142800, credit: 0 },
      { account: "Finished Goods Inventory", type: "Asset", debit: 348200, credit: 0 },
      { account: "Prepaid Insurance", type: "Asset", debit: 6750, credit: 0 },
      { account: "Studio Equipment", type: "Asset", debit: 235000, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 52500 },
      { account: "Intangible Assets", type: "Asset", debit: 90000, credit: 0 },
      { account: "Accumulated Amortization", type: "Contra-Asset", debit: 0, credit: 26250 },
      { account: "Accounts Payable", type: "Liability", debit: 0, credit: 318400 },
      { account: "Salaries Payable", type: "Liability", debit: 0, credit: 18400 },
      { account: "Notes Payable", type: "Liability", debit: 0, credit: 97500 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 600000 },
      { account: "Retained Earnings", type: "Equity", debit: 0, credit: 49300 },
      { account: "Wholesale Revenue", type: "Revenue", debit: 0, credit: 742000 },
      { account: "Retail Revenue", type: "Revenue", debit: 0, credit: 524800 },
      { account: "Licensing Income", type: "Revenue", debit: 0, credit: 45000 },
      { account: "COGS", type: "Expense", debit: 504000, credit: 0 },
      { account: "Salaries & Wages", type: "Expense", debit: 252000, credit: 0 },
      { account: "Rent", type: "Expense", debit: 72000, credit: 0 },
      { account: "Marketing", type: "Expense", debit: 66000, credit: 0 },
      { account: "Utilities", type: "Expense", debit: 14250, credit: 0 },
      { account: "Depreciation", type: "Expense", debit: 22500, credit: 0 },
      { account: "Amortization", type: "Expense", debit: 11250, credit: 0 },
    ],
  },
  {
    label: "Merchandising Case Study",
    period: "Practice Set",
    company: "fashion-house",
    theme: "Case Study",
    summary:
      "Trial balance prepared for an intermediate accounting case study covering merchandising operations, AR aging, inventory FIFO and adjusting entries.",
    totalDebits: 577520,
    totalCredits: 577520,
    rows: [
      { account: "Cash", type: "Asset", debit: 48200, credit: 0 },
      { account: "Accounts Receivable", type: "Asset", debit: 92400, credit: 0 },
      { account: "Allowance for Doubtful Accounts", type: "Contra-Asset", debit: 0, credit: 4620 },
      { account: "Merchandise Inventory", type: "Asset", debit: 124800, credit: 0 },
      { account: "Office Supplies", type: "Asset", debit: 2400, credit: 0 },
      { account: "Prepaid Insurance", type: "Asset", debit: 3600, credit: 0 },
      { account: "Office Equipment", type: "Asset", debit: 48000, credit: 0 },
      { account: "Accumulated Depreciation", type: "Contra-Asset", debit: 0, credit: 14400 },
      { account: "Accounts Payable", type: "Liability", debit: 0, credit: 62800 },
      { account: "Salaries Payable", type: "Liability", debit: 0, credit: 4800 },
      { account: "Unearned Revenue", type: "Liability", debit: 0, credit: 6000 },
      { account: "Notes Payable", type: "Liability", debit: 0, credit: 25000 },
      { account: "Common Shares", type: "Equity", debit: 0, credit: 80000 },
      { account: "Retained Earnings", type: "Equity", debit: 0, credit: 57120 },
      { account: "Dividends", type: "Equity", debit: 12000, credit: 0 },
      { account: "Sales Revenue", type: "Revenue", debit: 0, credit: 322780 },
      { account: "COGS", type: "Expense", debit: 168000, credit: 0 },
      { account: "Salaries Expense", type: "Expense", debit: 48000, credit: 0 },
      { account: "Rent Expense", type: "Expense", debit: 12000, credit: 0 },
      { account: "Supplies Expense", type: "Expense", debit: 3600, credit: 0 },
      { account: "Insurance Expense", type: "Expense", debit: 1200, credit: 0 },
      { account: "Bad Debt Expense", type: "Expense", debit: 4620, credit: 0 },
      { account: "Depreciation Expense", type: "Expense", debit: 7200, credit: 0 },
      { account: "Interest Expense", type: "Expense", debit: 1500, credit: 0 },
    ],
  },
];
